name: "ğŸš€ Prettier Check and Write"

on:
  push:

jobs:
  pretty:
    name: "ğŸ¨ Run Prettier"
    runs-on: ubuntu-latest

    steps:
      - name: "ğŸ“‚ Checkout Code"
        uses: actions/checkout@v2

      - name: "âš™ï¸ Setup Node.js"
        uses: actions/setup-node@v2
        with:
          node-version: "21"

      - name: "ğŸ“¦ Install Pnpm"
        run: sudo npm i -g pnpm

      - name: "ğŸ“¦ Install Dependencies"
        run: pnpm install --no-frozen-lockfile

      - name: "âœï¸ Run Prettier Write"
        run: pnpm run pretty:write
